### ISSUE TITLE
COMPASS-4097: Fix mongodb-js-metrics test suite

### ISSUE THREAD

**Issue by imlucas** [mongodb-js/errors#17]
- run in electron-mocha renderer
- travis fails from what looks like stitch dep update

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received function hidden
--
at Function.from (buffer.js:313:9)
at fnv1a32 (/home/travis/build/mongodb-js/metrics/node_modules/bson/lib/bson/fnv1a.js:21:25)
at fnv1a24 (/home/travis/build/mongodb-js/metrics/node_modules/bson/lib/bson/fnv1a.js:39:18)
at Object.<anonymous> (/home/travis/build/mongodb-js/metrics/node_modules/bson/lib/bson/objectid.js:14:20)
at Module._compile (internal/modules/cjs/loader.js:1144:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
at Module.load (internal/modules/cjs/loader.js:993:32)
at Function.Module._load (internal/modules/cjs/loader.js:892:14)
at Module.require (internal/modules/cjs/loader.js:1033:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/travis/build/mongodb-js/metrics/node_modules/bson/lib/bson/bson.js:7:14)
at Module._compile (internal/modules/cjs/loader.js:1144:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
at Module.load (internal/modules/cjs/loader.js:993:32)
at Function.Module._load (internal/modules/cjs/loader.js:892:14)
at Module.require (internal/modules/cjs/loader.js:1033:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/travis/build/mongodb-js/metrics/node_modules/bson/index.js:1:12)
at Module._compile (internal/modules/cjs/loader.js:1144:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
at Module.load (internal/modules/cjs/loader.js:993:32)
at Function.Module._load (internal/modules/cjs/loader.js:892:14)
at Module.require (internal/modules/cjs/loader.js:1033:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/travis/build/mongodb-js/metrics/node_modules/mongodb-extjson/lib/ext_json.js:4:10)
at Module._compile (internal/modules/cjs/loader.js:1144:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
at Module.load (internal/modules/cjs/loader.js:993:32)
at Function.Module._load (internal/modules/cjs/loader.js:892:14)
at Module.require (internal/modules/cjs/loader.js:1033:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/travis/build/mongodb-js/metrics/node_modules/mongodb-extjson/index.js:2:17)
at Module._compile (internal/modules/cjs/loader.js:1144:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
at Module.load (internal/modules/cjs/loader.js:993:32)
at Function.Module._load (internal/modules/cjs/loader.js:892:14)
at Module.require (internal/modules/cjs/loader.js:1033:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/travis/build/mongodb-js/metrics/node_modules/mongodb-stitch/dist/node/client.js:28:23)
at Module._compile (internal/modules/cjs/loader.js:1144:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
at Module.load (internal/modules/cjs/loader.js:993:32)
at Function.Module._load (internal/modules/cjs/loader.js:892:14)
at Module.require (internal/modules/cjs/loader.js:1033:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/travis/build/mongodb-js/metrics/node_modules/mongodb-stitch/dist/node/index.js:8:15)
at Module._compile (internal/modules/cjs/loader.js:1144:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
at Module.load (internal/modules/cjs/loader.js:993:32)
at Function.Module._load (internal/modules/cjs/loader.js:892:14)
at Module.require (internal/modules/cjs/loader.js:1033:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/travis/build/mongodb-js/metrics/lib/trackers/stitch.js:3:14)
at Module._compile (internal/modules/cjs/loader.js:1144:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
at Module.load (internal/modules/cjs/loader.js:993:32)
at Function.Module._load (internal/modules/cjs/loader.js:892:14)
at Module.require (internal/modules/cjs/loader.js:1033:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/travis/build/mongodb-js/metrics/lib/trackers/index.js:4:11)
at Module._compile (internal/modules/cjs/loader.js:1144:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
at Module.load (internal/modules/cjs/loader.js:993:32)
at Function.Module._load (internal/modules/cjs/loader.js:892:14)
at Module.require (internal/modules/cjs/loader.js:1033:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/travis/build/mongodb-js/metrics/lib/index.js:5:16)
at Module._compile (internal/modules/cjs/loader.js:1144:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
at Module.load (internal/modules/cjs/loader.js:993:32)
at Function.Module._load (internal/modules/cjs/loader.js:892:14)
at Module.require (internal/modules/cjs/loader.js:1033:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/travis/build/mongodb-js/metrics/test/app.test.js:1:15)
at Module._compile (internal/modules/cjs/loader.js:1144:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
at Module.load (internal/modules/cjs/loader.js:993:32)
at Function.Module._load (internal/modules/cjs/loader.js:892:14)
at Module.require (internal/modules/cjs/loader.js:1033:19)
at require (internal/modules/cjs/helpers.js:72:18)
at /home/travis/build/mongodb-js/metrics/node_modules/mocha/lib/mocha.js:308:36
at Array.forEach (<anonymous>)
at Mocha.loadFiles (/home/travis/build/mongodb-js/metrics/node_modules/mocha/lib/mocha.js:305:14)
at Mocha.run (/home/travis/build/mongodb-js/metrics/node_modules/mocha/lib/mocha.js:846:10)
at Object.exports.singleRun (/home/travis/build/mongodb-js/metrics/node_modules/mocha/lib/cli/run-helpers.js:108:16)
at exports.runMocha (/home/travis/build/mongodb-js/metrics/node_modules/mocha/lib/cli/run-helpers.js:143:13)
at Object.exports.handler (/home/travis/build/mongodb-js/metrics/node_modules/mocha/lib/cli/run.js:305:3)
at Object.runCommand (/home/travis/build/mongodb-js/metrics/node_modules/yargs/lib/command.js:242:26)
at Object.parseArgs [as _parseArgs] (/home/travis/build/mongodb-js/metrics/node_modules/yargs/yargs.js:1104:24)
at Object.parse (/home/travis/build/mongodb-js/metrics/node_modules/yargs/yargs.js:566:25)
at Object.exports.main (/home/travis/build/mongodb-js/metrics/node_modules/mocha/lib/cli/cli.js:68:6)
at Object.<anonymous> (/home/travis/build/mongodb-js/metrics/node_modules/mocha/bin/mocha:133:29)
at Module._compile (internal/modules/cjs/loader.js:1144:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
at Module.load (internal/modules/cjs/loader.js:993:32)
at Function.Module._load (internal/modules/cjs/loader.js:892:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
at internal/main/run_main_module.js:17:47 {
code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
```

**Comment by imlucas** [comment]
Wrong repo. moved mongodb-js/metrics#32
